#include "ImpulseResponseGenerator.h"

#include <cmath>

namespace ReverbIR
{
    namespace
    {
        // Density/spread/character of the discrete early-reflection layer
        // per Space setting. `earlyWindowMs` is the span within which taps
        // are scattered (tap 0 is always forced to sample 0 - see
        // addEarlyReflections() below); `tapDecayFactor` is the geometric
        // per-tap amplitude falloff.
        struct SpaceCharacteristics
        {
            float earlyWindowMs;
            int numTaps;
            float tapDecayFactor;
        };

        SpaceCharacteristics characteristicsFor (SpaceType space)
        {
            switch (space)
            {
                case SpaceType::cathedral: return { 150.0f, 22, 0.85f };
                case SpaceType::chamber:   return { 35.0f, 8, 0.65f };
                case SpaceType::hall:
                default:                   return { 80.0f, 14, 0.75f };
            }
        }

        // Adds a sparse train of discrete, decaying early-reflection taps
        // into `data` (length `lengthSamples`, at `sampleRate`), scaled by
        // `gain` (the early side of the Early/Late Balance crossfade).
        // Uses its own deterministic Random stream, independent of the
        // diffuse-tail noise generated by the caller, so the early-
        // reflection pattern is reproducible without being correlated with
        // it. Tap 0 is always placed at sample 0 with fixed (non-jittered,
        // positive) amplitude - a proxy for the earliest/loudest reflection
        // off the nearest boundary - so the generated IR's onset never
        // depends on Space/Early-Late-Balance (Pre-Delay timing relies on
        // measuring that onset).
        void addEarlyReflections (float* data, int lengthSamples, double sampleRate,
                                   SpaceType space, float gain, juce::Random& random)
        {
            if (gain <= 0.0f || lengthSamples <= 0)
                return;

            const auto characteristics = characteristicsFor (space);
            const auto windowSamples = juce::jmax (1, static_cast<int> (std::round (characteristics.earlyWindowMs * 0.001 * sampleRate)));

            float tapAmplitude = gain;

            for (int tap = 0; tap < characteristics.numTaps; ++tap)
            {
                if (tap == 0)
                {
                    data[0] += tapAmplitude;
                }
                else
                {
                    const auto sampleIndex = juce::jlimit (0, lengthSamples - 1,
                                                            static_cast<int> (random.nextFloat() * static_cast<float> (windowSamples)));

                    const auto polarity = random.nextFloat() < 0.5f ? -1.0f : 1.0f;
                    // +/-15% amplitude jitter per tap, for a less mechanical
                    // reflection pattern than a pure geometric sequence.
                    const auto jitter = 0.85f + 0.3f * random.nextFloat();

                    data[sampleIndex] += tapAmplitude * polarity * jitter;
                }

                tapAmplitude *= characteristics.tapDecayFactor;
            }
        }
    }

    juce::AudioBuffer<float> generateProceduralImpulseResponse (double sampleRate,
                                                                  float decaySeconds,
                                                                  float dampingHz,
                                                                  int numChannels,
                                                                  SpaceType space,
                                                                  float earlyLateBalance01,
                                                                  bool freeze,
                                                                  int seed)
    {
        const auto clampedDecay = juce::jlimit (minDecaySeconds, maxDecaySeconds, decaySeconds);

        // Keep the damping cutoff comfortably below Nyquist regardless of
        // sample rate, mirroring the defensive clamping pattern used for
        // filter cutoffs elsewhere in the suite (see e.g. Overture's
        // clampBelowNyquist) - a cutoff at or above Nyquist would produce a
        // degenerate/unstable one-pole coefficient below.
        const auto nyquist = static_cast<float> (sampleRate * 0.5);
        const auto clampedDamping = juce::jlimit (minDampingHz, juce::jmin (maxDampingHz, nyquist * 0.9f), dampingHz);
        const auto clampedBalance = juce::jlimit (0.0f, 1.0f, earlyLateBalance01);

        const auto lengthSamples = juce::jmax (1, static_cast<int> (std::round (clampedDecay * sampleRate)));
        const auto channels = juce::jlimit (1, 2, numChannels);

        juce::AudioBuffer<float> impulseResponse (channels, lengthSamples);

        // One-pole low-pass coefficient (RC/exponential-smoothing form):
        // higher dampingHz -> smaller `a` -> less smoothing -> brighter tail.
        const auto a = std::exp (-juce::MathConstants<float>::twoPi * clampedDamping / static_cast<float> (sampleRate));

        // -60 dB (RT60) point at t == clampedDecay: ln(1000) = 6.907755...
        constexpr float negSixtyDbTimeConstant = 6.90775528f;
        const auto decayRate = negSixtyDbTimeConstant / clampedDecay;

        // Equal-power crossfade between the early-reflection layer (full
        // gain at balance == 0) and the diffuse late tail (full gain at
        // balance == 1), so sweeping Early/Late Balance has no dip in total
        // energy at intermediate settings. Freeze suppresses the early
        // layer entirely (see the SpaceType doc comment) and forces the
        // diffuse layer's envelope flat further down.
        const auto halfPi = juce::MathConstants<float>::halfPi;
        const auto lateGain = freeze ? 1.0f : std::sin (clampedBalance * halfPi);
        const auto earlyGain = freeze ? 0.0f : std::cos (clampedBalance * halfPi);

        for (int channel = 0; channel < channels; ++channel)
        {
            // Distinct, deterministic noise stream per channel and per
            // caller-supplied seed: decorrelated L/R tails are what gives a
            // procedurally generated IR any sense of stereo width, and
            // determinism (rather than juce::Random::getSystemRandom())
            // keeps this function's output reproducible for unit tests.
            juce::Random random (static_cast<juce::int64> (seed) * 104729 + static_cast<juce::int64> (channel) * 7919 + 17);

            auto* data = impulseResponse.getWritePointer (channel);
            float filterState = 0.0f;

            for (int i = 0; i < lengthSamples; ++i)
            {
                const auto whiteNoise = random.nextFloat() * 2.0f - 1.0f;
                filterState = (1.0f - a) * whiteNoise + a * filterState;

                const auto t = static_cast<float> (static_cast<double> (i) / sampleRate);
                // Freeze sustains the tail's spectral content instead of
                // decaying it: the envelope is flat (1.0) across the whole
                // buffer rather than the usual RT60-style exponential. It
                // is still bounded to `lengthSamples` (governed by Decay,
                // same as the non-frozen case) rather than being truly
                // infinite - a convolution engine processes a finite
                // kernel - see docs/architecture.md.
                const auto envelope = freeze ? 1.0f : std::exp (-t * decayRate);

                data[i] = filterState * envelope * lateGain;
            }

            // Independent deterministic stream from the diffuse-tail noise
            // above (different multiplier/offset), so the early-reflection
            // pattern doesn't correlate with it while staying reproducible.
            juce::Random earlyRandom (static_cast<juce::int64> (seed) * 40503 + static_cast<juce::int64> (channel) * 6151 + 101);
            addEarlyReflections (data, lengthSamples, sampleRate, space, earlyGain, earlyRandom);
        }

        return impulseResponse;
    }
}
